---
title: "Method"
author: '180000622'
date: "2023-08-06"
output: html_document
---

```{r}
library(tidyverse)
library(Rlibeemd)
library(EMD)
library(forecast)
library(hrbrthemes)
library(gridExtra)
library(ggpubr)
library(foreach)

setwd("~/MSc_Thesis_Supplementary_Material/functions")
source('significance_test_functions.R')
setwd("~/MSc_Thesis_Supplementary_Material")

```

```{r}
left_alligned_IMFs <- read_rds('left_alligned_IMFs.rds')
scaled_left_alligned_IMFs <- read_rds('scaled_left_alligned_IMFs.rds')

```

Extract and compare the IMFs

```{r}
# Function to do CEEMDAN
ceemdan_function <- function(series, scaled = FALSE) {
  
  # if scaled series are required, scale
  if (scaled == TRUE) {
    series <- (series - min(series))/(max(series) - min(series))
  }
  
  # first determine numer of IMFs to be computed:
  num_IMFs <- round(log2(length(unlist(series, use.names = FALSE))))
  
  # set parameters:
  ensemble <- 250
  siftings <- 750
  S <- 6 # the highest range in documentation
  noise = 0.2 # as suggested in documentation
  seed = 343
  
  # do CEEMDAN with preset parameters
  IMFs <- Rlibeemd::ceemdan(series, num_imfs = num_IMFs, 
                  ensemble_size = ensemble, 
                  num_siftings = siftings,
                  S_number = S,
                  noise_strength = noise,
                  rng_seed = seed)
  
  # convert to a data frame, and add the original series on to the end
  IMFs_df <- IMFs %>% as.data.frame() %>% mutate(series = series)
  
  return(IMFs_df)
}
```

```{r}
ticker <- 'ULVR'

ticker_IMFs_list <- left_alligned_IMFs[[ticker]]
scaled_ticker_IMFs_list <- scaled_left_alligned_IMFs[[ticker]]

IMF_t1 <-ticker_IMFs_list$IMF_data[[2]]
scaled_IMF_t1 <-scaled_ticker_IMFs_list$IMF_data[[2]]
```

```{r}
# get generation dates
generation_dates <- IMF_t1$generation_dates %>% as_date()

# get announcement days
announcement_index <- match(ticker_IMFs_list$announcements, generation_dates) %>% na.omit() 
announcement_df <- data.frame(index = announcement_index)
```

Get price and price change:

```{r}

# import price data for the period [T, T+g+1]
price_data <- read_rds('master_stock_prices.rds')

ticker_price <- price_data[price_data$ticker == ticker, ]

matching_dates <- match(generation_dates, ticker_price$date) %>% range()

# extract matching prices with a padding on eaither side for differencing
gen_period_prices <- ticker_price[(matching_dates[1]-1):(matching_dates[2]+1), ]

ticker_prices_df <- gen_period_prices %>% select(date, price) %>% mutate(date = as_date(date), log_price = log(price), log_returns = c(NA, diff(log_price)[1:(length(log_price)-1)]), price_change = c(NA, diff(price)[1:(length(price)-1)]))
```

Now do CEEMDAN on price and on price change

```{r}

# decomose the series
# discard first two rows of the IMFs so that they are the samre length as the forecast IMF
IMFs_price <- ceemdan_function(ticker_prices_df$price)[3:nrow(ticker_prices_df), ]
scaled_IMFs_price <- ceemdan_function(ticker_prices_df$price, scaled = TRUE)[3:nrow(ticker_prices_df), ]


IMFs_change <- ceemdan_function(na.omit(ticker_prices_df$price_change))[2:(nrow(ticker_prices_df)-1), ]
scaled_IMFs_change <- ceemdan_function(na.omit(ticker_prices_df$price_change, scaled = TRUE))[2:(nrow(ticker_prices_df)-1), ]
```

Now we have our decomposed series, we can plot them as time series plots:

```{r}
# g+1 time series:
g1 <- IMF_t1$IMFs[[1]] %>% mutate(g = as.numeric(rownames(IMF_t1$IMFs[[1]])))

# plot
score_plot <- g1 %>% select(series, g) %>%
  ggplot(aes(x = g, y = series)) + geom_line(color = 'darkcyan') +
  geom_vline(data = announcement_df, aes(xintercept = index), linetype = 'dashed',
             alpha = 0.4) +
  labs(y = 'Expectation Score') +
  theme_minimal(base_size = 6) +
    theme(axis.title.x = element_blank(),
          plot.margin = unit(c(0.5, 5.5, 0.5, 5.5), "pt"))

IMF_ts_func <- function(df, IMF, color = 'darkcyan') {
  df %>% pivot_longer(-g) %>% filter(name == IMF) %>%
  ggplot(aes(x = g, y = value)) + geom_line(color = color) +
  geom_vline(data = announcement_df, aes(xintercept = index), linetype = 'dashed',
             alpha = 0.4) +
  labs(y = paste(IMF)) +
  theme_minimal(base_size = 6) +
    theme(axis.title.x = element_blank(),
          plot.margin = unit(c(0.5, 5.5, 0.5, 5.5), "pt"))
}

IMF_score_plots <- lapply(names(g1)[1:8], IMF_ts_func, df = g1)
```

```{r}
grid_score <- grid.arrange(score_plot, arrangeGrob(IMF_score_plots[[1]], IMF_score_plots[[2]],
                                     IMF_score_plots[[3]], IMF_score_plots[[4]],
                                     IMF_score_plots[[5]], IMF_score_plots[[6]],
                                     IMF_score_plots[[7]], (IMF_score_plots[[8]] + labs(x = 'Generation Day, g')+ theme_minimal(base_size = 6) +
    theme(plot.margin = unit(c(0.5, 5.5, 5.5, 5.5), "pt"))), nrow = 8), heights = c(0.25,1))
```

```{r}
# prices
IMFs_price <-  IMFs_price %>% mutate(g = as.numeric(rownames(IMFs_price))-1)

price_plot <- IMFs_price %>%
  ggplot(aes(x = g, y = series)) + geom_line(color = 'darkred') +
  geom_vline(data = announcement_df, aes(xintercept = index), linetype = 'dashed',
             alpha = 0.4) +
  labs(y = 'ULVR Price Close') +
  theme_minimal(base_size = 6) +
    theme(axis.title.x = element_blank(),
          plot.margin = unit(c(0.5, 5.5, 0.5, 5.5), "pt"))

IMF_price_plots <- lapply(names(IMFs_price)[1:8], IMF_ts_func, df = IMFs_price, color = 'darkred')

```

```{r}
grid_price <- grid.arrange(price_plot, arrangeGrob(IMF_price_plots[[1]], IMF_price_plots[[2]],
                                     IMF_price_plots[[3]], IMF_price_plots[[4]],
                                     IMF_price_plots[[5]], IMF_price_plots[[6]],
                                     IMF_price_plots[[7]], (IMF_price_plots[[8]] + labs(x = 'Generation Day, g')+ theme_minimal(base_size = 6) +
    theme(plot.margin = unit(c(0.5, 5.5, 5.5, 5.5), "pt"))), nrow = 8), heights = c(0.25,1))
```

```{r}
# price change
IMFs_change <-  IMFs_change %>% mutate(g = as.numeric(rownames(IMFs_change)))

change_plot <- IMFs_change %>%
  ggplot(aes(x = g, y = series)) + geom_line(color = 'darkmagenta') +
  geom_vline(data = announcement_df, aes(xintercept = index), linetype = 'dashed',
             alpha = 0.4) +
  labs(y = 'ULVR Price Change') +
  theme_minimal(base_size = 6) +
    theme(axis.title.x = element_blank(),
          plot.margin = unit(c(0.5, 5.5, 0.5, 5.5), "pt"))

IMF_change_plots <- lapply(names(IMFs_change)[1:8], IMF_ts_func, df = IMFs_change, color = 'darkmagenta')

```

```{r}
grid_change <- grid.arrange(change_plot, arrangeGrob(IMF_change_plots[[1]], IMF_change_plots[[2]],
                                     IMF_change_plots[[3]], IMF_change_plots[[4]],
                                     IMF_change_plots[[5]], IMF_change_plots[[6]],
                                     IMF_change_plots[[7]], (IMF_change_plots[[8]] + labs(x = 'Generation Day, g')+ theme_minimal(base_size = 6) +
    theme(plot.margin = unit(c(0.5, 5.5, 5.5, 5.5), "pt"))), nrow = 8), heights = c(0.25,1))
```

```{r}
# bring them together:

grid.arrange(grid_score, grid_price, grid_change, ncol = 3)
```

```{r}
amp_freq_g1 <- EMD::hilbertspec(IMF_t1$IMFs[[1]][,1:7])

IMF_names <- names(IMFs_change)[1:7]
freq_1 <- as.data.frame(amp_freq_g1$instantfreq) %>% set_names(IMF_names)  

freq_1 <- freq_1 %>% mutate(g = as.numeric(rownames(freq_1)))

freq_score_plots <- lapply(IMF_names, IMF_ts_func, df = freq_1)

freq_score_grid <- grid.arrange(freq_score_plots[[1]], freq_score_plots[[2]],freq_score_plots[[3]], freq_score_plots[[4]],
                                freq_score_plots[[5]],freq_score_plots[[6]],(freq_score_plots[[7]] + 
                                     labs(x = 'Generation Day, g') +
                                     theme_minimal(base_size = 6) +
                                     theme(plot.margin = unit(c(0.5, 5.5, 5.5, 5.5), "pt"))), nrow = 7)

```

```{r}
amp_freq_price <- EMD::hilbertspec(IMFs_price[,1:7])


freq_price <- as.data.frame(amp_freq_price$instantfreq) %>% set_names(IMF_names)  

# set g so that price is correct
freq_price <- freq_price %>% mutate(g = (as.numeric(rownames(IMFs_price))-1))

freq_price_plots <- lapply(IMF_names, IMF_ts_func, df = freq_price, color = 'darkred')

freq_price_grid <- grid.arrange(freq_price_plots[[1]], freq_price_plots[[2]],freq_price_plots[[3]], freq_price_plots[[4]],
                                freq_price_plots[[5]],freq_price_plots[[6]],(freq_price_plots[[7]] + 
                                     labs(x = 'Generation Day, g') +
                                     theme_minimal(base_size = 6) +
                                     theme(plot.margin = unit(c(0.5, 5.5, 5.5, 5.5), "pt"))), nrow = 7)

```

```{r}
amp_freq_change <- EMD::hilbertspec(IMFs_change[,1:7])


freq_change <- as.data.frame(amp_freq_change$instantfreq) %>% set_names(IMF_names)  

freq_change <- freq_change %>% mutate(g = as.numeric(rownames(IMFs_change)))

freq_change_plots <- lapply(IMF_names, IMF_ts_func, df = freq_change, color = 'darkmagenta')

freq_change_grid <- grid.arrange(freq_change_plots[[1]], freq_change_plots[[2]],freq_change_plots[[3]], freq_change_plots[[4]],
                                freq_change_plots[[5]],freq_change_plots[[6]],(freq_change_plots[[7]] + 
                                     labs(x = 'Generation Day, g') +
                                     theme_minimal(base_size = 6) +
                                     theme(plot.margin = unit(c(0.5, 5.5, 5.5, 5.5), "pt"))), nrow = 7)

```

```{r}
grid.arrange(arrangeGrob(freq_score_grid, top =  grid::textGrob("Expectations, g+1", gp = grid::gpar(fontsize = 8))),
             arrangeGrob(freq_price_grid, top =  grid::textGrob("ULVR Price Close", gp = grid::gpar(fontsize = 8))),
             arrangeGrob(freq_change_grid, top =  grid::textGrob("Price Change", gp = grid::gpar(fontsize = 8))), left =  grid::textGrob("Instantaneous Frequency", rot = 90, gp = grid::gpar(fontsize = 10)),  ncol = 3)
```

Now for Amplitude:
```{r}
amp_1 <- as.data.frame(amp_freq_g1$amplitude) %>% set_names(IMF_names)  

amp_1 <- amp_1 %>% mutate(g = (as.numeric(rownames(amp_1))))

amp_score_plots <- lapply(IMF_names, IMF_ts_func, df = amp_1)

amp_score_grid <- grid.arrange(amp_score_plots[[1]], amp_score_plots[[2]],amp_score_plots[[3]], amp_score_plots[[4]],
                                amp_score_plots[[5]],amp_score_plots[[6]],(amp_score_plots[[7]] + 
                                     labs(x = 'Generation Day, g') +
                                     theme_minimal(base_size = 6) +
                                     theme(plot.margin = unit(c(0.5, 5.5, 5.5, 5.5), "pt"))), nrow = 7)

```

```{r}
amp_price <- as.data.frame(amp_freq_price$amplitude) %>% set_names(IMF_names)  

amp_price <- amp_price %>% mutate(g = (as.numeric(rownames(IMFs_price))-1))

amp_price_plots <- lapply(IMF_names, IMF_ts_func, df = amp_price, color = 'darkred')

amp_price_grid <- grid.arrange(amp_price_plots[[1]], amp_price_plots[[2]],amp_price_plots[[3]], amp_price_plots[[4]],
                                amp_price_plots[[5]],amp_price_plots[[6]],(amp_price_plots[[7]] + 
                                     labs(x = 'Generation Day, g') +
                                     theme_minimal(base_size = 6) +
                                     theme(plot.margin = unit(c(0.5, 5.5, 5.5, 5.5), "pt"))), nrow = 7)

```

```{r}
amp_change <- as.data.frame(amp_freq_change$amplitude) %>% set_names(IMF_names)  

amp_change <- amp_change %>% mutate(g = (as.numeric(rownames(IMFs_change))))

amp_change_plots <- lapply(IMF_names, IMF_ts_func, df = amp_change, color = 'darkmagenta')

amp_change_grid <- grid.arrange(amp_change_plots[[1]], amp_change_plots[[2]],amp_change_plots[[3]], amp_change_plots[[4]],
                                amp_change_plots[[5]],amp_change_plots[[6]],(amp_change_plots[[7]] + 
                                     labs(x = 'Generation Day, g') +
                                     theme_minimal(base_size = 6) +
                                     theme(plot.margin = unit(c(0.5, 5.5, 5.5, 5.5), "pt"))), nrow = 7)

```

```{r}
grid.arrange(arrangeGrob(amp_score_grid, top =  grid::textGrob("Expectations, g+1", gp = grid::gpar(fontsize = 8))),
             arrangeGrob(amp_price_grid, top =  grid::textGrob("ULVR Price Close", gp = grid::gpar(fontsize = 8))),
             arrangeGrob(amp_change_grid, top =  grid::textGrob("Price Change", gp = grid::gpar(fontsize = 8))), left =  grid::textGrob("Instantaneous Amplitude", rot = 90, gp = grid::gpar(fontsize = 10)),  ncol = 3)
```

# Recomposing the original series
```{r}
IMFs_price <- IMFs_price %>% mutate(low = Residual + `IMF 7` + `IMF 6`,
                                          mid = `IMF 5` + `IMF 4` + `IMF 3`,
                                    low_mid = low+mid,
                                    g = as.numeric(rownames(IMFs_price))+1)


composed_plot <- IMFs_price %>% select(g,low, low_mid) %>% pivot_longer(-g) %>%
  ggplot(aes(x = g)) + 
  geom_line(aes(y = value, color = name)) +
  geom_vline(data = announcement_df, aes(xintercept = index), linetype = 'dashed',
             alpha = 0.4) +
  scale_color_discrete(name = 'IMFs', labels = c('Last 3', 'Last 6') ) +
  labs(x = 'g',
       y = 'Price Close') +
  theme_minimal(base_size = 10) 

composed_plot + geom_line(data = IMFs_price, aes(x = g, y = series), alpha = 0.4) 
```
```{r}
IMFs_change <- IMFs_change %>% mutate(low = Residual + `IMF 7` + `IMF 6`,
                                          mid = `IMF 5` + `IMF 4` + `IMF 3`,
                                    low_mid = low+mid,
                                    g = as.numeric(rownames(IMFs_change))+1)


composed_plot <- IMFs_change %>% select(g,low, low_mid) %>% pivot_longer(-g) %>%
  ggplot(aes(x = g)) + 
  geom_line(aes(y = value, color = name)) +
  geom_vline(data = announcement_df, aes(xintercept = index), linetype = 'dashed',
             alpha = 0.4) +
  scale_color_discrete(name = 'IMFs', labels = c('Last 3', 'Last 6') ) +
  labs(x = 'g',
       y = 'Price Change') +
  theme_minimal(base_size = 10) 

composed_plot + geom_line(data = IMFs_change, aes(x = g, y = series), alpha = 0.4) 
```

## Reconstructing the score heatmap

```{r}
#Make the basic heatmap
ULVR_IMFs <- left_alligned_IMFs$ULVR$IMF_data[[2]]$IMFs

ULVR_original <- foreach(g1 = ULVR_IMFs, .combine = bind_rows) %do% {
  g1$series
}

ULVR_original %>% mutate(future = as.numeric(rownames(ULVR_original))) %>% pivot_longer(-future) %>%
  ggplot(aes(x = future, y = as.numeric(name), fill = value))+
  geom_tile()  +
  geom_hline(data = announcement_df, aes(yintercept = index), alpha = 0.7, linetype = 'dashed') +
  scale_y_reverse() +
  scale_fill_gradient2(high = 'blue', mid = 'white', low = 'red', na.value = 'lightgrey') +
  labs(x = 'h',
       y = 'g',
       fill = NULL) +
  theme_minimal( base_size = 10)
    
```

```{r}
#Make the low pass heatmap
ULVR_low_pass <- left_alligned_IMFs$ULVR$IMF_data[[2]]$IMFs

ULVR_low_pass <- foreach(g1 = ULVR_IMFs) %do% {
   g1$Residual + g1$`IMF 7` + g1$`IMF 6`
}
ULVR_low_pass <- ULVR_low_pass %>% set_names(as.character(seq(1, length(ULVR_low_pass)))) %>% bind_cols()

ULVR_low_pass %>% mutate(g = as.numeric(rownames(ULVR_low_pass))) %>% pivot_longer(-g) %>%
  ggplot(aes(y = g, x = as.numeric(name), fill = value))+
  geom_tile()  +
  geom_hline(data = announcement_df, aes(yintercept = index), alpha = 0.7, linetype = 'dashed') +
  scale_y_reverse() +
  scale_fill_gradient2(high = 'blue', mid = 'white', low = 'red', na.value = 'lightgrey',
                       limits = c(-1,1)) +
  labs(x = 'h',
       y = 'g',
       fill = NULL) +
  theme_minimal( base_size = 6)
    
```

```{r}
#Make the mid pass heatmap

ULVR_mid_pass <- foreach(g1 = ULVR_IMFs) %do% {
   g1$`IMF 5` + g1$`IMF 4` + g1$`IMF 3`
}
ULVR_mid_pass <- ULVR_mid_pass %>% set_names(as.character(seq(1, length(ULVR_mid_pass)))) %>% bind_cols()

ULVR_mid_pass %>% mutate(g = as.numeric(rownames(ULVR_mid_pass))) %>% pivot_longer(-g) %>%
  ggplot(aes(y = g, x = as.numeric(name), fill = value))+
  geom_tile()  +
  geom_hline(data = announcement_df, aes(yintercept = index), alpha = 0.7, linetype = 'dashed') +
  scale_y_reverse() +
  scale_fill_gradient2(high = 'blue', mid = 'white', low = 'red', na.value = 'lightgrey', limits = c(-1,1)) +
  labs(x = 'h',
       y = 'g',
       fill = NULL) +
  theme_minimal( base_size = 6)
    
```

```{r}
#Make the high pass heatmap

ULVR_high_pass <- foreach(g1 = ULVR_IMFs) %do% {
  g1$high_pass =  g1$`IMF 1` + g1$`IMF 2`
}
ULVR_high_pass <- ULVR_high_pass %>% set_names(as.character(seq(1, length(ULVR_high_pass)))) %>% bind_cols()

ULVR_high_pass %>% mutate(g = as.numeric(rownames(ULVR_high_pass))) %>% pivot_longer(-g) %>%
  ggplot(aes(y = g, x = as.numeric(name), fill = value))+
  geom_tile()  +
  geom_hline(data = announcement_df, aes(yintercept = index), alpha = 0.7, linetype = 'dashed') +
  scale_y_reverse() +
  scale_fill_gradient2(high = 'blue', mid = 'white', low = 'red', na.value = 'lightgrey',limits = c(-1,1)) +
  labs(x = 'h',
       y = 'g',
       fill = NULL) +
  theme_minimal( base_size = 6)
    
```

```{r}
#Make the composed heatmap

ULVR_filtered <- ULVR_low_pass + ULVR_mid_pass 
ULVR_filtered <- ULVR_filtered %>% set_names(as.character(seq(1, length(ULVR_filtered)))) %>% bind_cols()

ULVR_filtered %>% mutate(g = as.numeric(rownames(ULVR_filtered))) %>% pivot_longer(-g) %>%
  ggplot(aes(y = g, x = as.numeric(name), fill = value))+
  geom_tile()  +
  geom_hline(data = announcement_df, aes(yintercept = index), alpha = 0.7, linetype = 'dashed') +
  scale_y_reverse() +
  scale_fill_gradient2(high = 'blue', mid = 'white', low = 'red', na.value = 'lightgrey') +
  labs(x = 'h',
       y = 'g',
       fill = NULL) +
  theme_minimal( base_size = 10)
    
```